use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::Arc;
use std::time::Duration;

use coding_agent_core::WorkspaceFingerprint;
use coding_agent_runtime::{
    DeliverySourceError, DeliverySourceLimits, DeliverySourceProvisioner, ExecutionDirectory,
    FingerprintLimits, PinnedExecutable, ProbedDeliveryGit, ProcessLimits, ToolchainPaths,
    WorkspaceFingerprinter, WorktreeIdentity, WorktreeLimits, WorktreeProvisioner,
    WorktreeReservation, discover_toolchain, probe_delivery_git,
};
use tempfile::TempDir;
use tokio_util::sync::CancellationToken;

use super::support;

const REPOSITORY_ID: &str = "delivery-security-repository";
const TASK_ID: &str = "123e4567-e89b-12d3-a456-426614174003";

pub struct SecurityFixture {
    // This proof guard must drop before the TempDir removes its sentinel
    // namespace.
    process_scopes: support::ProcessScopeTracker,
    _temporary: TempDir,
    pub root: PathBuf,
    pub runtime: PathBuf,
    probe_root: PathBuf,
    pub repository: PathBuf,
    pub admin_directory: PathBuf,
    pub worktree: PathBuf,
    pub toolchain: ToolchainPaths,
    pub probed_git: Arc<ProbedDeliveryGit>,
    pub worktree_provisioner: WorktreeProvisioner,
    pub reservation: WorktreeReservation,
}

impl SecurityFixture {
    pub async fn new() -> Self {
        let test_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target");
        std::fs::create_dir_all(&test_root).unwrap();
        let temporary = tempfile::Builder::new()
            .prefix("delivery-security-")
            .tempdir_in(test_root)
            .unwrap();
        // Normalize away `..` while retaining a child-visible DOS path on
        // Windows. Raw `canonicalize` adds a `\\?\` namespace prefix which
        // Git persists as `//?/...` and later rejects as an include path.
        let root = child_visible_path(&temporary.path().canonicalize().unwrap());
        let runtime = root.join("runtime");
        let repository = root.join("repository");
        let artifact_root = root.join("artifacts");
        let probe_root = root.join("probe");
        for directory in [
            &runtime,
            &repository.join("src"),
            &artifact_root,
            &probe_root,
        ] {
            std::fs::create_dir_all(directory).unwrap();
        }

        git_ok(&repository, &["init", "--quiet"]);
        git_ok(
            &repository,
            &["config", "user.name", "Delivery Security Test"],
        );
        git_ok(
            &repository,
            &["config", "user.email", "delivery-security@example.invalid"],
        );
        std::fs::write(repository.join("tracked.txt"), b"reviewed base\n").unwrap();
        std::fs::write(
            repository.join("Cargo.toml"),
            b"[workspace]\n\n[package]\nname = \"delivery_security_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .unwrap();
        std::fs::write(
            repository.join("src/lib.rs"),
            b"pub fn committed() -> bool { true }\n",
        )
        .unwrap();
        std::fs::write(
            repository.join("Cargo.lock"),
            b"# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"delivery_security_fixture\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        git_ok(&repository, &["add", "--all"]);
        git_ok(
            &repository,
            &["commit", "--quiet", "--no-gpg-sign", "-m", "base"],
        );

        let process_scopes = support::ProcessScopeTracker::default();
        let toolchain = discover_toolchain(
            &runtime,
            process_scopes.track(support::instance_process_scope(&runtime)),
            Some(&concrete_rustc()),
            Some(&path_executable(if cfg!(windows) {
                "git.exe"
            } else {
                "git"
            })),
        )
        .await
        .unwrap();
        let probed_git = Arc::new(
            probe_delivery_git(
                toolchain.git(),
                Arc::new(ExecutionDirectory::open(&probe_root).unwrap()),
                process_scopes.track(support::task_process_scope(&runtime)),
                process_limits(),
                Duration::from_secs(15),
                CancellationToken::new(),
            )
            .await
            .unwrap(),
        );
        let worktree_provisioner = WorktreeProvisioner::from_trusted_paths(
            &toolchain,
            REPOSITORY_ID,
            &repository,
            &repository,
            &artifact_root,
            &runtime,
            process_scopes.track(support::task_process_scope(&runtime)),
            process_limits(),
            WorktreeLimits::try_new(Duration::from_secs(15)).unwrap(),
        )
        .unwrap();
        let identity = WorktreeIdentity::try_new(REPOSITORY_ID, TASK_ID, 1).unwrap();
        std::fs::create_dir_all(
            artifact_root
                .join(identity.relative_path())
                .parent()
                .unwrap(),
        )
        .unwrap();
        let reservation = worktree_provisioner
            .prepare(identity, CancellationToken::new())
            .await
            .unwrap();
        let provisioned = worktree_provisioner
            .provision_reserved(reservation.clone(), CancellationToken::new())
            .await
            .unwrap();
        let worktree = provisioned.worktree_path().to_owned();
        let admin_directory = single_admin_directory(&repository);
        std::fs::write(worktree.join("tracked.txt"), b"exact reviewed change\n").unwrap();
        drop(provisioned);

        Self {
            process_scopes,
            _temporary: temporary,
            root,
            runtime,
            probe_root,
            repository,
            admin_directory,
            worktree,
            toolchain,
            probed_git,
            worktree_provisioner,
            reservation,
        }
    }

    pub fn source_provisioner(&self) -> Result<DeliverySourceProvisioner, DeliverySourceError> {
        self.source_provisioner_with_limits(delivery_source_limits())
    }

    pub fn source_provisioner_with_limits(
        &self,
        limits: DeliverySourceLimits,
    ) -> Result<DeliverySourceProvisioner, DeliverySourceError> {
        self.source_provisioner_with_probe_and_limits(Arc::clone(&self.probed_git), limits)
    }

    pub fn source_provisioner_with_probe(
        &self,
        probed_git: Arc<ProbedDeliveryGit>,
    ) -> Result<DeliverySourceProvisioner, DeliverySourceError> {
        self.source_provisioner_with_probe_and_limits(probed_git, delivery_source_limits())
    }

    pub fn source_provisioner_with_temporary_directory(
        &self,
        temporary_directory: &Path,
    ) -> Result<DeliverySourceProvisioner, DeliverySourceError> {
        DeliverySourceProvisioner::from_worktree_provisioner(
            &self.worktree_provisioner,
            Arc::clone(&self.probed_git),
            temporary_directory,
            self.task_process_scope(),
            process_limits(),
            delivery_source_limits(),
            fingerprint_limits(),
        )
    }

    pub async fn independently_probed_git(&self) -> Arc<ProbedDeliveryGit> {
        let probe_root = self.root.join("independent-probe");
        std::fs::create_dir(&probe_root).unwrap();
        let independently_pinned_git = Arc::new(
            PinnedExecutable::open(path_executable(if cfg!(windows) {
                "git.exe"
            } else {
                "git"
            }))
            .unwrap(),
        );
        Arc::new(
            probe_delivery_git(
                independently_pinned_git,
                Arc::new(ExecutionDirectory::open(&probe_root).unwrap()),
                self.task_process_scope(),
                process_limits(),
                Duration::from_secs(15),
                CancellationToken::new(),
            )
            .await
            .unwrap(),
        )
    }

    fn source_provisioner_with_probe_and_limits(
        &self,
        probed_git: Arc<ProbedDeliveryGit>,
        limits: DeliverySourceLimits,
    ) -> Result<DeliverySourceProvisioner, DeliverySourceError> {
        DeliverySourceProvisioner::from_worktree_provisioner(
            &self.worktree_provisioner,
            probed_git,
            &self.probe_root,
            self.task_process_scope(),
            process_limits(),
            limits,
            fingerprint_limits(),
        )
    }

    pub async fn fingerprint(&self) -> WorkspaceFingerprint {
        let ready = self
            .worktree_provisioner
            .open_ready(&self.reservation, CancellationToken::new())
            .await;
        assert!(
            ready.is_err(),
            "the P4-A clean-worktree entry point must remain closed for a dirty source"
        );

        let git_directory = Arc::new(ExecutionDirectory::open(&self.admin_directory).unwrap());
        let work_tree = Arc::new(ExecutionDirectory::open(&self.worktree).unwrap());
        WorkspaceFingerprinter::from_trusted_capabilities(
            &self.toolchain,
            git_directory,
            work_tree,
            &self.runtime,
            self.task_process_scope(),
            process_limits(),
            fingerprint_limits(),
        )
        .unwrap()
        .collect(CancellationToken::new())
        .await
        .unwrap()
    }

    pub fn set_common_config(&self, key: &str, value: &str) {
        git_ok(
            &self.repository,
            &["config", "--local", "--no-includes", key, value],
        );
    }

    pub fn unset_common_config(&self, key: &str) {
        let output = git_output(
            &self.repository,
            &["config", "--local", "--no-includes", "--unset-all", key],
        );
        assert!(
            output.status.success() || output.status.code() == Some(5),
            "failed to unset test Git config {key}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    pub fn config_worktree(&self) -> PathBuf {
        self.admin_directory.join("config.worktree")
    }

    fn task_process_scope(&self) -> coding_agent_runtime::ProcessLivenessScope {
        self.process_scopes
            .track(support::task_process_scope(&self.runtime))
    }
}

pub fn process_limits() -> ProcessLimits {
    ProcessLimits::try_new(
        512 * 1024,
        512 * 1024,
        Duration::from_secs(30),
        Duration::from_secs(5),
    )
    .unwrap()
}

fn delivery_source_limits() -> DeliverySourceLimits {
    delivery_source_limits_with(256 * 1024, 64 * 1024, 64 * 1024, 4_096)
}

pub fn delivery_source_limits_with(
    max_status_bytes: usize,
    max_config_bytes: usize,
    max_attributes_bytes: usize,
    max_paths: usize,
) -> DeliverySourceLimits {
    DeliverySourceLimits::try_new(
        Duration::from_secs(15),
        max_status_bytes,
        max_config_bytes,
        max_attributes_bytes,
        max_paths,
    )
    .unwrap()
}

fn fingerprint_limits() -> FingerprintLimits {
    FingerprintLimits::try_new(
        Duration::from_secs(15),
        4_096,
        1024 * 1024,
        16 * 1024 * 1024,
    )
    .unwrap()
}

fn single_admin_directory(repository: &Path) -> PathBuf {
    let mut entries = std::fs::read_dir(repository.join(".git/worktrees"))
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .collect::<Vec<_>>();
    assert_eq!(
        entries.len(),
        1,
        "fixture must create exactly one linked worktree"
    );
    entries.pop().unwrap().canonicalize().unwrap()
}

fn git_ok(repository: &Path, arguments: &[&str]) {
    let output = git_output(repository, arguments);
    assert!(
        output.status.success(),
        "Git fixture command failed: git -C {} {}\nstdout: {}\nstderr: {}",
        repository.display(),
        arguments.join(" "),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn git_output(repository: &Path, arguments: &[&str]) -> Output {
    support::command_output(
        Command::new("git")
            .arg("--no-pager")
            .arg("-c")
            .arg(git_hooks_path_configuration())
            .arg("-c")
            .arg("commit.gpgSign=false")
            .arg("-C")
            .arg(repository)
            .args(arguments)
            .env("GIT_CONFIG_NOSYSTEM", "1")
            .env("GIT_CONFIG_GLOBAL", null_device())
            .env("GIT_TERMINAL_PROMPT", "0"),
    )
    .unwrap()
}

fn concrete_rustc() -> PathBuf {
    let output =
        support::command_output(Command::new("rustc").args(["--print", "sysroot"])).unwrap();
    assert!(output.status.success());
    PathBuf::from(String::from_utf8(output.stdout).unwrap().trim())
        .join("bin")
        .join(if cfg!(windows) { "rustc.exe" } else { "rustc" })
        .canonicalize()
        .unwrap()
}

fn path_executable(name: &str) -> PathBuf {
    std::env::split_paths(&std::env::var_os("PATH").unwrap())
        .map(|directory| directory.join(name))
        .find(|candidate| candidate.is_file())
        .unwrap()
        .canonicalize()
        .unwrap()
}

#[cfg(unix)]
fn child_visible_path(path: &Path) -> PathBuf {
    path.to_owned()
}

#[cfg(windows)]
fn child_visible_path(path: &Path) -> PathBuf {
    use std::path::{Component, Prefix};

    let mut components = path.components();
    let Some(Component::Prefix(prefix)) = components.next() else {
        return path.to_owned();
    };
    let Prefix::VerbatimDisk(drive) = prefix.kind() else {
        return path.to_owned();
    };
    if !matches!(components.next(), Some(Component::RootDir)) {
        return path.to_owned();
    }
    let mut visible = PathBuf::from(format!("{}:\\", char::from(drive)));
    for component in components {
        if let Component::Normal(name) = component {
            visible.push(name);
        }
    }
    visible
}

#[cfg(windows)]
fn git_hooks_path_configuration() -> &'static str {
    "core.hooksPath=NUL"
}

#[cfg(unix)]
fn git_hooks_path_configuration() -> &'static str {
    "core.hooksPath=/dev/null"
}

#[cfg(windows)]
fn null_device() -> &'static str {
    "NUL"
}

#[cfg(unix)]
fn null_device() -> &'static str {
    "/dev/null"
}
