use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::Arc;

use coding_agent_app::{CodingAttemptError, RepositoryWorktreeProvisionerFactory};
use coding_agent_domain::{CanonicalPath, Repository};
use coding_agent_runtime::{
    ProcessLimits, ProcessLivenessScope, ToolchainPaths, WorktreeLimits, WorktreeProvisioner,
    discover_toolchain,
};

use super::{
    COMMITTED_STAGED, COMMITTED_UNSTAGED, INITIAL_SOURCE, PROCESS_CLEANUP_TIMEOUT,
    PROCESS_COMMAND_TIMEOUT, WORKTREE_ORCHESTRATION_TIMEOUT,
};

pub(super) async fn discover_e2e_toolchain(
    runtime_directory: &Path,
    instance_process_scope: ProcessLivenessScope,
) -> ToolchainPaths {
    let rustc = concrete_rustc();
    let git = path_executable(if cfg!(windows) { "git.exe" } else { "git" });
    discover_toolchain(
        runtime_directory,
        instance_process_scope,
        Some(rustc.as_path()),
        Some(git.as_path()),
    )
    .await
    .expect("discover concurrent E2E toolchain")
}

pub(super) fn provisioner_factory(
    toolchain: ToolchainPaths,
    artifact_root: PathBuf,
    runtime_directory: PathBuf,
) -> Arc<dyn RepositoryWorktreeProvisionerFactory> {
    Arc::new(
        move |repository: &Repository,
              process_liveness_scope: ProcessLivenessScope|
              -> Result<Arc<WorktreeProvisioner>, CodingAttemptError> {
            WorktreeProvisioner::from_trusted_paths(
                &toolchain,
                repository.id.to_string(),
                repository.git_root.as_path(),
                repository.cargo_workspace_root.as_path(),
                &artifact_root,
                &runtime_directory,
                process_liveness_scope,
                ProcessLimits::try_new(
                    512 * 1024,
                    256 * 1024,
                    PROCESS_COMMAND_TIMEOUT,
                    PROCESS_CLEANUP_TIMEOUT,
                )
                .expect("valid concurrent E2E process limits"),
                WorktreeLimits::try_new(WORKTREE_ORCHESTRATION_TIMEOUT)
                    .expect("valid concurrent E2E worktree limits"),
            )
            .map(Arc::new)
            .map_err(|error| CodingAttemptError::new(error.code(), false))
        },
    )
}

pub(super) fn seed_repository(repository: &Path) {
    git_ok(repository, &["init", "--quiet"]);
    git_ok(
        repository,
        &["config", "user.name", "Concurrent Offline E2E"],
    );
    git_ok(
        repository,
        &[
            "config",
            "user.email",
            "concurrent-offline-e2e@example.invalid",
        ],
    );
    std::fs::write(
        repository.join("Cargo.toml"),
        b"[workspace]\n\n[package]\nname = \"offline_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write E2E Cargo manifest");
    std::fs::write(
        repository.join("Cargo.lock"),
        b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"offline_fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write E2E Cargo lockfile");
    std::fs::write(repository.join(".gitignore"), b"/target/\n").expect("write E2E ignore file");
    std::fs::write(repository.join("src/lib.rs"), INITIAL_SOURCE).expect("write E2E source");
    std::fs::write(
        repository.join("tests/answer.rs"),
        b"#[test]\nfn answer_is_forty_two() { assert_eq!(offline_fixture::answer(), 42); }\n",
    )
    .expect("write E2E integration test");
    std::fs::write(repository.join("staged.txt"), COMMITTED_STAGED)
        .expect("write committed staged sentinel");
    std::fs::write(repository.join("unstaged.txt"), COMMITTED_UNSTAGED)
        .expect("write committed unstaged sentinel");
    git_ok(repository, &["add", "--all"]);
    git_ok(
        repository,
        &["commit", "--quiet", "--no-gpg-sign", "-m", "base"],
    );
}

pub(super) fn canonical(path: &Path) -> CanonicalPath {
    CanonicalPath::try_from_canonical(path.canonicalize().expect("canonical fixture path"))
        .expect("domain canonical path")
}

pub(super) fn git_ok(repository: &Path, arguments: &[&str]) {
    let output = git_output(repository, arguments);
    assert!(
        output.status.success(),
        "git {} failed: {}",
        arguments.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
}

pub(super) fn git_line(repository: &Path, arguments: &[&str]) -> String {
    let output = git_output(repository, arguments);
    assert!(
        output.status.success(),
        "git {} failed: {}",
        arguments.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout)
        .expect("Git output is UTF-8")
        .trim()
        .to_owned()
}

pub(super) fn git_bytes(repository: &Path, arguments: &[&str]) -> Vec<u8> {
    let output = git_output(repository, arguments);
    assert!(
        output.status.success(),
        "git {} failed: {}",
        arguments.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    output.stdout
}

pub(super) fn git_optional_ref(repository: &Path, reference: &str) -> Option<String> {
    let output = git_output(repository, &["show-ref", "--quiet", "--verify", reference]);
    match output.status.code() {
        Some(0) => Some(git_line(repository, &["rev-parse", reference])),
        Some(1) => None,
        other => panic!(
            "git show-ref --verify returned {other:?}: {}",
            String::from_utf8_lossy(&output.stderr)
        ),
    }
}

fn git_output(repository: &Path, arguments: &[&str]) -> Output {
    super::super::command_output(
        Command::new(path_executable(if cfg!(windows) {
            "git.exe"
        } else {
            "git"
        }))
        .arg("-C")
        .arg(repository)
        .args(arguments),
    )
    .expect("run fixture Git")
}

fn concrete_rustc() -> PathBuf {
    let output = super::super::command_output(Command::new("rustc").args(["--print", "sysroot"]))
        .expect("query Rust sysroot");
    assert!(output.status.success());
    PathBuf::from(
        String::from_utf8(output.stdout)
            .expect("Rust sysroot is UTF-8")
            .trim(),
    )
    .join("bin")
    .join(if cfg!(windows) { "rustc.exe" } else { "rustc" })
    .canonicalize()
    .expect("canonical rustc")
}

fn path_executable(name: &str) -> PathBuf {
    let candidate = std::env::split_paths(&std::env::var_os("PATH").expect("host PATH"))
        .map(|directory| directory.join(name))
        .find(|candidate| candidate.is_file())
        .unwrap_or_else(|| panic!("{name} missing from PATH"))
        .canonicalize()
        .expect("canonical executable");
    #[cfg(windows)]
    if name.eq_ignore_ascii_case("git.exe")
        && candidate.parent().is_some_and(|parent| {
            parent
                .file_name()
                .is_some_and(|name| name.eq_ignore_ascii_case("cmd"))
        })
    {
        let installation = candidate
            .parent()
            .expect("Git cmd directory")
            .parent()
            .expect("Git installation directory");
        for architecture in ["mingw64", "mingw32"] {
            let concrete = installation.join(architecture).join("bin/git.exe");
            if concrete.is_file() {
                return concrete.canonicalize().expect("canonical concrete Git");
            }
        }
    }
    candidate
}
